const res = await fetch('http://127.0.0.1:3080/plugins/dsh-better-sidebar-lite/client.js?rev=c296000a7b2b')
const js = await res.text()
console.log('len:', js.length)
console.log('has shell.overlay:', js.includes('shell.overlay'))
console.log('has better-sidebar: service + dock:', js.includes('better-sidebar: service + dock'))
console.log('has betterSidebar.tabs.register:', js.includes('register'))
console.log('has explorer id:', js.includes('id: "explorer"') || js.includes('"explorer"'))
console.log('has git id:', js.includes('"git"'))
console.log('has resolveRoot:', js.includes('resolveRoot'))
